# Lab 1: Tensor Manipulation

First Author: Seungjae Ryan Lee (seungjaeryanlee at gmail dot com)
Second Author: Ki Hyun Kim (nlp.with.deep.learning at gmail dot com)

<div class="alert alert-warning">
    NOTE: This corresponds to <a href="https://www.youtube.com/watch?v=ZYX0FaqUeN4&t=23s&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm&index=25">Lab 8 of Deep Learning Zero to All Season 1 for TensorFlow</a>.
</div>

## Imports

Run `pip install -r requirements.txt` in terminal to install all required Python packages.

In [1]:
import numpy as np
import torch

## NumPy Review

We hope that you are familiar with `numpy` and basic linear algebra.

### 1D Array with NumPy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with NumPy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


## PyTorch is like NumPy (but better)

### 1D Array with PyTorch

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())  # rank 몇 차원인지? 
print(t.shape)  # shape 모양은 어떤지?
print(t.size()) # shape 
print(t[0], t[1], t[-1])  # Element acccess 가능
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])  # 1번째 차원에서 다 가져오기, 2번째 차원은 index 1만 가져오기
print(t[:, 1].size())  # 크기 (shape)은 어떤지
print(t[:, :-1]) # 1번째 차원에서 다 가져오기, 2번째 차원은 마지막거 전까지 가져오기

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [11]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [12]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operations in PyTorch

### Mul vs. Matmul

In [13]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
# 행렬 곱 : 뒤에 차원-앞의 차원 일치해야함.
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1 ==> broad casting으로 (2,2)뙴
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


mul 계산 시 broadcasting 된 것 시각화

![Mul 실행 시 브로드 케스트 된 경우](./images/Lab01-1-1.png)

### Broadcasting

<div class="alert alert-warning">
    Carelessly using broadcasting can lead to code hard to debug.
</div>

자동으로 사이즈를 맞추어 때문에 굉장히 조심해서 사용해야함!

In [16]:
# Same shape
m1 = torch.FloatTensor([[3, 3]]) # |m1| = (1,2) size
m2 = torch.FloatTensor([[2, 2]]) # |m1| = |m2|
print(m1 + m2)

tensor([[5., 5.]])


In [15]:
# Vector + scalar 다른 크기 인 경우 -> 자동으로 Pytorch 에서 사이즈 조정해줌
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]] ==> |m2| = (1,) => (1,2)
print(m1 + m2)

tensor([[4., 5.]])


In [16]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # |m1| = (1,2)
m2 = torch.FloatTensor([[3], [4]]) # |m2| = (2,1) 
# |m1| + |m2| = (2,2) 서로 사이즈 맞추어줌
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mean

In [17]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [18]:
# Can't use mean() on integers
# FloatTensor만 평균 구하는 것이 가능하다.
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use `t.mean` for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [20]:
print(t.mean())
# -> (1+3)/2 , (2+4) / 2
print(t.mean(dim=0))
# | 
# v (1+2)/ 2, (3+4) / 2
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [20]:
print(t.sum())
# 첫 번째 dimension [(1+3) , (2+4)]
print(t.sum(dim=0))
# 두 번째 dimension [(1+2) , (3+4)]
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The `max` operator returns one value if it is called without an argument.

In [24]:
print(t.max()) # Returns one value: max

tensor(4.)


The `max` operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax: the index of the element with maximum value.

In [25]:
# 첫번째 dimension에 대해 처리 [max(1,3) , max(2,4)] , max 값들의 index인 argmax : [1,1] 
print(t.max(dim=0)) # Returns two values: max and argmax(index) 
# argmax라고 index도 같이 return 됨
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

(tensor([3., 4.]), tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [26]:
print(t.max(dim=1))
print(t.max(dim=-1))

(tensor([2., 4.]), tensor([1, 1]))
(tensor([2., 4.]), tensor([1, 1]))


### View

numpy에서 reshape와 같은 역할
shape를 다시 만들어주겠다.

<div class="alert alert-warning">
    This is a function hard to master, but is very useful!
</div>

In [21]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
# |ft| = (2,2,3) -> 밖에서부터 들어가는 듯
# [[[0,1,2],[3,4,5]]  ,   [[6,7,8],[9,10,11]]] 2개
# [[0,1,2]  ,   [3,4,5]] 2개
# [0,  1,  2]  3개

torch.Size([2, 2, 3])


In [22]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape) # (2x2, 3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [29]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) # (2x2,1,3)로 reshape -1은 상대적으로 준 값인 듯

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

수건을 쥐어 짤 때 쓰는 단어
view와 다르게 자동으로 원하는 dimension 수정 가능 (dimension 삭제 가능)

In [24]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape) # |ft| = (3,1)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [25]:
print(ft.squeeze(dim=0)) #이면 변화 x
print(ft.squeeze()) # (3,1)에서 쥐어 짜내서 3만 남김
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [26]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape) # |ft| = (3,)

torch.Size([3])


In [27]:
print(ft.unsqueeze(0)) # (dim = 0)에 1을 넣어라
print(ft.unsqueeze(0).shape) # (!,3)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [34]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [35]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [36]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


![unsqueeeze](./images/Lab01-2-1.png)

### Scatter (for one-hot encoding)

<div class="alert alert-warning">
    Scatter is a very flexible function. We only discuss how to use it to get a one-hot encoding of indices.
</div>

In [28]:
# longTensor로 선언함
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [30]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting

In [31]:
# longTensor로 선언함
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [40]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [32]:
bt = (lt == 3)
print(bt) # lt가 3인 것은 true 1, 아닌 것은 false 0

tensor([0, 0, 1, 0], dtype=torch.uint8)


In [33]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [34]:
# byte -> long, float
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

In [36]:
x = torch.FloatTensor([[1, 2], [3, 4]]) # (2,2)
y = torch.FloatTensor([[5, 6], [7, 8]]) # (2,2)

dimension 0에 대해

In [37]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


![위에 것에 대한 설명](./images/Lab01-2-2.png)

dimension 1에 대해

In [38]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


![위에 것에 대한 설명](./images/Lab01-2-3.png)

### Stacking

concating을 편리하게 하도록 함

In [40]:
x = torch.FloatTensor([1, 4]) # |x| = |y| = |Z| = (2,)
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [42]:
print(torch.stack([x, y, z])) # list의 x,y,z는 tensor를 가짐

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


![위의 모양 형태](./images/Lab01-2-4.png)

In [43]:
# dimension 1에 대해서 쌓아라.
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


![위의 모양 형태](./images/Lab01-2-5.png)

In [46]:
# unsqueeze한 후, cat하는 것과 동일한 결과
# (1,2) , (1,2) , (1,2)로 만듬
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like

In [47]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x) # |x| = (2,3)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [49]:
# 1로만 가득찬 똑같은 사이즈의 torch
print(torch.ones_like(x))
# 0로만 가득찬 똑같은 사이즈의 torch
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [49]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [50]:
print(x.mul(2.)) # x에 곱하기 2를 해라, x가 바뀌지는 않음
print(x) 
print(x.mul_(2.)) # x가 변형됨 (garbage collector가 파이썬은 잘 되어 있으므로 필요 없을 수도 있음..ㅎ)
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


## Miscellaneous

### Zip

In [52]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [53]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
